FROM python:3.12-slim AS runtime
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y ffmpeg && \
    apt-get clean

FROM runtime
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
WORKDIR /app
COPY ./main.py .
COPY ./src/ ./src
ENTRYPOINT [ "python", "main.py" ]
