services:
  consumer:
    build: 
      dockerfile: Dockerfile.consumer
      context: .
    environment:
      SERVER_ENDPOINT: "http://producer:8080"
    command: client
    depends_on:
      - producer
  
  producer:
    build:
      dockerfile: Dockerfile.producer
      context: .
    ports:
      - 8080:8080
    command: server
