services:
  consumer:
    build:
      dockerfile: Dockerfile.consumer
      context: .
    environment:
      SERVER_ENDPOINT: "http://api.kamuridesu.com/api/ytdl"
    command: client
  consumer1:
    build:
      dockerfile: Dockerfile.consumer
      context: .
    environment:
      SERVER_ENDPOINT: "http://api.kamuridesu.com/api/ytdl"
    command: client
#  producer:
#    build:
#      dockerfile: Dockerfile.producer
#      context: .
#    ports:
#      - 8080:8080
#    command: server
